### PR TITLE
feat: astro-font - optimize fonts & prevent CLS

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
https://www.launchfa.st/features/astro-font

### CODE REVIEW

**Comment by vogelino** [comment]
Hi @rishi-raj-jain ! I appreciate the help! Your package seems to fulfil a good purpose. Unfortunately the PR breaks the font loading. Notice how the vercel preview differs from the production page: https://vogelino.com. The fonts are simply not the same. It seems to use the fallback... :(

**Comment by rishi-raj-jain** [comment]
@vogelino 

Investigating...

**Comment by rishi-raj-jain** [comment]
@vogelino

may u re-approve deploy?

**Comment by rishi-raj-jain** [comment]
@vogelino

may u re-approve deploy?

**Comment by rishi-raj-jain** [comment]
@vogelino 

I think all good now?

**Comment by vogelino** [comment]
@rishi-raj-jain I appreciate the help. It seems to load the font this time, even if it does introduce some bugs. Removing the tailwind config and then overriding tailwindcss classes with global important CSS doesn't seem like a good idea. Additionally, when the fonts load the flash even more that before leading to a worsen UX (Even if I noticed a smaller layout shift with your package). Can you please explain what the package is doing and how it improve the current state of my website?

Again, I'm open to try out your package. However, right now it isn't a drop in replacement and doesn't noticeably improve the font loading. I am reticent to add an additional dependency without any good argumentation. Can you help me to convince myself? Thx!

**Comment by rishi-raj-jain** [comment]
> tailwind config and then overriding tailwindcss classes with global important CSS doesn't seem like a good idea.

I've taken care of this. Nothing is overriden!

**Comment by rishi-raj-jain** [comment]
> it isn't a drop in replacement

I think now it does look like one, with

- removed preloads
- removed CSS manually to write fonts

The `<AstroFont />` just comes in and throws out optimized fonts with CSS font variables.

**Comment by rishi-raj-jain** [comment]
> I am reticent to add an additional dependency without any good argumentation.

Yeah, that does make sense, let's go ahead and deploy this version for you to take a look?

**Comment by rishi-raj-jain** [comment]
> I appreciate the help. 

> Again, I'm open to try out your package.

I appreciate your openness to it. Thank you!

Here's some of the production websites using `astro-font` that might help you convince a bit: https://www.launchfa.st/blog/astro-font-showcase

**Comment by rishi-raj-jain** [comment]
@vogelino 

Let me find some time this week and get back to you.

**Pull request closed without merging**
